
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class frame4 extends javax.swing.JFrame {

    /**
     * Creates new form frame4
     */
    public frame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bola = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpanjangBalok = new javax.swing.JTextField();
        jlebarbalok = new javax.swing.JTextField();
        jtinggibalok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bla = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setText("Masukan Panjang  :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 11, 130, 27);

        jLabel3.setText("Masukan Lebar :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 50, 130, 30);

        jLabel4.setText("Masukan Tinggi :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 90, 130, 30);

        jpanjangBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpanjangBalokActionPerformed(evt);
            }
        });
        jPanel1.add(jpanjangBalok);
        jpanjangBalok.setBounds(150, 10, 130, 30);
        jPanel1.add(jlebarbalok);
        jlebarbalok.setBounds(150, 50, 130, 30);

        jtinggibalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggibalokActionPerformed(evt);
            }
        });
        jPanel1.add(jtinggibalok);
        jtinggibalok.setBounds(150, 90, 130, 30);

        jLabel5.setText("CM");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 100, 34, 14);

        jLabel6.setText("CM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 10, 30, 20);

        jLabel7.setText("CM");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 60, 34, 14);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 133, 100, 30);

        bola.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setText("Masukan Panjang SISI");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(46, 11, 150, 20);
        jPanel2.add(sisi);
        sisi.setBounds(30, 40, 100, 40);

        jLabel9.setText("CM");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(140, 44, 30, 20);

        jButton2.setText("Volume");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(60, 120, 67, 23);

        bola.addTab("kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Masukan Panjang jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(46, 11, 150, 20);
        jPanel3.add(bla);
        bla.setBounds(30, 40, 100, 40);

        jLabel11.setText("CM");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(140, 44, 30, 20);

        jButton3.setText("Volume");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(60, 120, 67, 23);

        bola.addTab("Bola", jPanel3);

        getContentPane().add(bola);
        bola.setBounds(0, 80, 400, 220);

        jLabel1.setText("Tabel perhitungan volume bangun ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 14, 230, 40);

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 400, 300);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jtinggibalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggibalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggibalokActionPerformed

    private void jpanjangBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpanjangBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanjangBalokActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int panjang, lebar , tinggi;
        panjang=Integer.parseInt(jpanjangBalok.getText());
         lebar=Integer.parseInt(jlebarbalok.getText());
          tinggi=Integer.parseInt(jtinggibalok.getText());
          int hasil = panjang*lebar*tinggi;
          try{
              JOptionPane.showMessageDialog(null,"Volume Balok adalah :" +hasil,"Luas",JOptionPane.INFORMATION_MESSAGE);
          } catch (Exception e){
              JOptionPane.showMessageDialog(null,"Error" +e,"Gagal", 
                      JOptionPane.WARNING_MESSAGE);
          }
                  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int bl;
        bl = Integer.parseInt(bla.getText());
        
        int hasil = 4/3* 22/7 *bl*bl*bl;
         try{
              JOptionPane.showMessageDialog(null,"Volume Bola adalah :" +hasil,"Luas",JOptionPane.INFORMATION_MESSAGE);
          } catch (Exception e){
              JOptionPane.showMessageDialog(null,"Error" +e,"Gagal", 
                      JOptionPane.WARNING_MESSAGE);
          }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int volume;
        volume = Integer.parseInt(sisi.getText());
        
        int hasil = volume*volume*volume;
         try{
              JOptionPane.showMessageDialog(null,"Volume kubus adalah :" +hasil,"Luas",JOptionPane.INFORMATION_MESSAGE);
          } catch (Exception e){
              JOptionPane.showMessageDialog(null,"Error" +e,"Gagal", 
                      JOptionPane.WARNING_MESSAGE);
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bla;
    private javax.swing.JTabbedPane bola;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jlebarbalok;
    private javax.swing.JTextField jpanjangBalok;
    private javax.swing.JTextField jtinggibalok;
    private javax.swing.JTextField sisi;
    // End of variables declaration//GEN-END:variables
}
